---
# Update1: Deploy Index Web Page
# Update2: Deploy Info Template Web Page
# Update3: Smart Playbook with When Candation.
# Update4: Local Varibales in playbook & Templates


- hosts: mysrv
  name: My Apache Server Installation
  become: yes

  vars:
    doc_root: "/var/www/html"
    username: "Amit Kumar" 

  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start Apache Service
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"

  - name: Install http Packages on CentOS
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start http Service on CentOS
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"
     
  - name: Deploy Index Page
    copy: src=templates/index.html dest={{doc_root}}/index.html

  - name: Deploy Info Template Page
    template: src=templates/info.j2 dest={{doc_root}}/info.html

- hosts: db
  name: Getting Ready with Git Clinet
  become: yes 

  tasks:
  - name: Install GIT Packages
    apt: name=git state=present
