---
# tasks file for webserver
- name: Install Apache Packages
  apt: name=apache2 state=present
  when: ansible_os_family == "Debian"

- name: Start Apache Service
  service: name=apache2 state=started
  when: ansible_os_family == "Debian"

- name: Install http Packages on CentOS
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Start http Service on CentOS
  service: name=httpd state=started
  when: ansible_os_family == "RedHat"

- name: Deploy Index Page
  copy: src=files/index.html dest={{doc_root}}/index.html

- name: Download Mario Background Image
  get_url: url=http://www.mariomayhem.com/downloads/wallpapers/24/mushroom_1024_x_768.jpg dest={{doc_root}}/mario.jpg mode=0755

- name: Deploy Info Template Page
  template: src=templates/info.j2 dest={{doc_root}}/info.html
